# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('precio', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
