# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
