# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20161214_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
    ]
