# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20161214_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='id_sede',
            field=models.ForeignKey(db_column='id_sede', on_delete=django.db.models.deletion.CASCADE, to='sedes.Sede'),
        ),
    ]
